### ISSUE TITLE
Selezione tank in access manager

### ISSUE THREAD

**Issue by enricuez92** [uniquid/dev-in-a-box#4] opened 2017-12-20 11:48 UTC
non posso selezionare tutte le tank perchè non sono visibili nel menu a tendina.
<img width="1235" alt="schermata 2017-12-20 alle 12 46 50" src="https://user-images.githubusercontent.com/25021103/34205773-1242a256-e584-11e7-8cc8-471b88429ab7.png">

**Comment by g0dz1ll4** [comment] 2017-12-20 11:55
Thanks @enricuez92 for your feedback. 
Please can you provide a description in English to keep understandable for all ? 
Anyway what branch you're using?

**Comment by g0dz1ll4** [comment] 2017-12-28 14:41
@enricuez92 You use branch develop.
The issue occurred in the dashboard service is now fixed and upgraded on this repo.
You can perform a pull of the branch.
The issue is closed.

**Closed** 2017-12-28 14:42 UTC
